[project]
name = "python-polars-the-definitive-guide"
version = "1.0.0"
description = "Scripts and datasets for the O'Reilly book Python Polars: The Definitive Guide "
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "chardet>=5.2.0",
    "datashader>=0.16.3",
    "numpy<2",
    "geoviews>=1.13.0",
    "ipykernel>=6.29.5",
    "jupyterlab>=4.3.1",
    "lxml>=5.3.0",
    "maturin>=1.7.4",
    "pip>=24.3.1",
    "plotnine>=0.14.1",
    "polars[all]>=1.13.1",
    "hvplot>=0.11.1",
    "textblob>=0.18.0.post0",
    "scikit-learn>=1.5.2",
    "jupyter-bokeh>=4.0.5",
]
